### ISSUE TITLE
'Object of class Faker\Generator could not be converted to number'

### ISSUE THREAD

**Issue by Azam2926** [yii-starter-kit/yii2-starter-kit#774]
azam@inoyatov:/var/www/cazoo$ **php console/yii app/demo-data**
**PHP Notice** **'yii\base\ErrorException'** with message '**Object of class Faker\Generator could not be converted to number'**

in /var/www/cazoo/console/controllers/AppController.php:230

Stack trace:
#0 /var/www/cazoo/console/controllers/AppController.php(230): yii\base\ErrorHandler->handleError()
#1 /var/www/cazoo/console/controllers/AppController.php(167): console\controllers\AppController->addArticles()
#2 [internal function]: console\controllers\AppController->actionDemoData()
#3 /var/www/cazoo/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#4 /var/www/cazoo/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#5 /var/www/cazoo/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#6 /var/www/cazoo/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#7 /var/www/cazoo/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#8 /var/www/cazoo/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#9 /var/www/cazoo/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#10 /var/www/cazoo/console/yii(26): yii\base\Application->run()
#11 {main}

![Screenshot from 2021-03-03 23-57-02](https://user-images.githubusercontent.com/28877486/109857149-2e545600-7c7c-11eb-9f09-b9b05b78b56d.png)

**Comment by Azam2926** [comment]
**$factory-**  this is something special ha
