### ISSUE TITLE
npm run build Error: Cannot find module 'less'

### ISSUE THREAD

**Issue by mysoundmagic** [yii-starter-kit/yii2-starter-kit#784]
I get this error when following manual installation step number 4 on the installation.md
how to resolve this?

> @ build /home/ubuntu/Documents/workspace/blogapp
> webpack --progress

Hash: bd9fe2a3bf19a54dc2e6a72c2b580a7f358eb305
Version: webpack 4.46.0
Child
    Hash: bd9fe2a3bf19a54dc2e6
    Time: 769ms
    Built at: 09/05/2022 13:34:16
           Asset      Size  Chunks                   Chunk Names
          app.js  3.89 KiB     app  [emitted]        app
      app.js.map  3.65 KiB     app  [emitted] [dev]  app
        style.js  10.4 KiB   style  [emitted]        style
    style.js.map  3.54 KiB   style  [emitted] [dev]  style
    Entrypoint app = app.js app.js.map
    Entrypoint style = style.js style.js.map
    [./frontend/web/css/style.less] 6.56 KiB {style} [built] [failed] [1 error]
    [./frontend/web/js/app.js] 71 bytes {app} [built]
    
    ERROR in ./frontend/web/css/style.less
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/less-loader/lib/loader.js):
    Error: Cannot find module 'less'
    Require stack:
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compiler.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/webpack.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/validate-options.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/convert-argv.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/cli.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/bin/webpack.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js:3:14)
        at Module._compile (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:739:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:1111:12
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:409:6
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:155:13
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/Hook.js:154:20)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:138:29
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:346:9
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:316:20
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:172:11
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:32:11)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:739:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:1111:12
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:409:6
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:155:13
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/Hook.js:154:20)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:138:29
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:346:9
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/less-loader/lib/loader.js!frontend/web/css/style.less:
        Entrypoint mini-css-extract-plugin = *
        [./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/lib/loader.js!./frontend/web/css/style.less] 4.1 KiB {mini-css-extract-plugin} [not cacheable] [built] [failed] [1 error]
        
        ERROR in ./frontend/web/css/style.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/lib/loader.js!./frontend/web/css/style.less)
        Module build failed (from ./node_modules/less-loader/lib/loader.js):
        Error: Cannot find module 'less'
        Require stack:
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compiler.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/webpack.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/validate-options.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/convert-argv.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/cli.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/bin/webpack.js
            at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
            at Function.Module._load (internal/modules/cjs/loader.js:725:27)
            at Module.require (internal/modules/cjs/loader.js:952:19)
            at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
            at Object.<anonymous> (/home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js:3:14)
            at Module._compile (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
            at Module.load (internal/modules/cjs/loader.js:928:32)
            at Function.Module._load (internal/modules/cjs/loader.js:769:14)
            at Module.require (internal/modules/cjs/loader.js:952:19)
            at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
            at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:18:17)
            at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
            at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
            at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
            at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
            at runLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
            at NormalModule.doBuild (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:295:3)
            at NormalModule.build (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:446:15)
            at Compilation.buildModule (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:739:10)
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:1111:12
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:409:6
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:155:13
            at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
            at AsyncSeriesWaterfallHook.lazyCompileHook (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/Hook.js:154:20)
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:138:29
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:346:9
            at processTicksAndRejections (internal/process/task_queues.js:75:11)
Child
    Hash: a72c2b580a7f358eb305
    Time: 750ms
    Built at: 09/05/2022 13:34:16
           Asset      Size  Chunks                   Chunk Names
          app.js  3.85 KiB     app  [emitted]        app
      app.js.map  3.63 KiB     app  [emitted] [dev]  app
        style.js  10.4 KiB   style  [emitted]        style
    style.js.map  3.54 KiB   style  [emitted] [dev]  style
    Entrypoint app = app.js app.js.map
    Entrypoint style = style.js style.js.map
    [./backend/web/css/style.less] 6.56 KiB {style} [built] [failed] [1 error]
    [./backend/web/js/app.js] 33 bytes {app} [built]
    
    ERROR in ./backend/web/css/style.less
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/less-loader/lib/loader.js):
    Error: Cannot find module 'less'
    Require stack:
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compiler.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/webpack.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/validate-options.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/convert-argv.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/cli.js
    - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/bin/webpack.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js:3:14)
        at Module._compile (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:739:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:1111:12
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:409:6
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:155:13
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/Hook.js:154:20)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:138:29
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:346:9
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:316:20
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:172:11
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:32:11)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:739:10)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:1111:12
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:409:6
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:155:13
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/Hook.js:154:20)
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:138:29
        at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:346:9
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/less-loader/lib/loader.js!backend/web/css/style.less:
        Entrypoint mini-css-extract-plugin = *
        [./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/lib/loader.js!./backend/web/css/style.less] 4.1 KiB {mini-css-extract-plugin} [not cacheable] [built] [failed] [1 error]
        
        ERROR in ./backend/web/css/style.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/lib/loader.js!./backend/web/css/style.less)
        Module build failed (from ./node_modules/less-loader/lib/loader.js):
        Error: Cannot find module 'less'
        Require stack:
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compiler.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/webpack.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/validate-options.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/utils/convert-argv.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack-cli/bin/cli.js
        - /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/bin/webpack.js
            at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
            at Function.Module._load (internal/modules/cjs/loader.js:725:27)
            at Module.require (internal/modules/cjs/loader.js:952:19)
            at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
            at Object.<anonymous> (/home/ubuntu/Documents/workspace/blogapp/node_modules/less-loader/lib/loader.js:3:14)
            at Module._compile (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
            at Module.load (internal/modules/cjs/loader.js:928:32)
            at Function.Module._load (internal/modules/cjs/loader.js:769:14)
            at Module.require (internal/modules/cjs/loader.js:952:19)
            at require (/home/ubuntu/Documents/workspace/blogapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
            at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:18:17)
            at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
            at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:176:18
            at loadLoader (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/loadLoader.js:47:3)
            at iteratePitchingLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
            at runLoaders (/home/ubuntu/Documents/workspace/blogapp/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
            at NormalModule.doBuild (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:295:3)
            at NormalModule.build (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModule.js:446:15)
            at Compilation.buildModule (/home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:739:10)
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/Compilation.js:1111:12
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:409:6
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:155:13
            at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
            at AsyncSeriesWaterfallHook.lazyCompileHook (/home/ubuntu/Documents/workspace/blogapp/node_modules/tapable/lib/Hook.js:154:20)
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:138:29
            at /home/ubuntu/Documents/workspace/blogapp/node_modules/webpack/lib/NormalModuleFactory.js:346:9
            at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `webpack --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-05-09T06_34_16_657Z-debug.log

** Software Versions **

| Q                | A
| ---------------- | ---
| Yii version    | 2.0.45
| PHP version      | PHP Version 7.4.3
| Operating system | ubuntu 20.04.4

**Comment by rivieiraa** [comment]
npm i less
